Intake
FTC-Team-Tiewraps-23452/FTC-Team-Tiewraps-23452-Buildseason-24-25 pull request #2
Opened 2024-10-24 14:22 UTC by Sebastiaap

pull request for the intake subsystem

2024-10-24 15:06 UTC, MarkKonijnenburg requested changes
Lekker bezig! Doe eerst de Lift, dan de Intake. Zijn redelijk wat de zelfde standaard verbetering. Wederom, het is niet fout, maar kan efficiënter!

2024-10-24 15:06 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +    }
Weer het zelfde, 2 praktisch de zelfde functies met alleen een andere targetPositie. Vraag die positie op via de functie zoals je het ook met de snelheid kan doen.

2024-10-24 15:06 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +        storeMotor = hardwareMap.get(DcMotor.class, "store");
Maak even een consistente naamgeving voor motoren. Hier gebruik je de naam 'store' en bij lift 'motor4', 2 totaal verschillende namen dat is verwarrend. Pas of deze naam aan, of die van de lift.

2024-10-24 15:21 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +    //all of the following functions need to be tuned and tested
ja dit heb ik al gedaan, staat verder boven in de code.

2024-10-24 15:23 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +    //all of the following functions need to be tuned and tested
Miss dan de tekst weghalen? is verwarrend voor later

2024-10-24 16:37 UTC, MarkKonijnenburg requested changes
miss moet er nog iets worden aangepast...

2024-10-24 16:37 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +    }
Kan je hier ook geen 1 functie van maken?

2024-10-24 16:37 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Intake.java
> +    }
mooi spull

2024-10-25 10:18 UTC, MarkKonijnenburg approved these changes

2024-10-25 10:35 UTC, merged