Lift
FTC-Team-Tiewraps-23452/FTC-Team-Tiewraps-23452-Buildseason-24-25 pull request #3
Opened 2024-10-24 14:23 UTC by Sebastiaap

pull request for the lift subsystem

2024-10-24 14:56 UTC, MarkKonijnenburg requested changes
Overal is goed! In principe is niks fout, maar kan efficiënter/beter!
Lekker bezigg!!!

2024-10-24 14:56 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Lift.java
> +    }
Nu heb je eigenlijk 3 dezelfde functies met alleen een andere snelheid, is te veeeeel code. Je kan beter 1 functie maken die de snelheid opvraagt en de motor zet op die snelheid. Pas het dan ook aan in de TeleOp.
Het is niet fout, maar dit is efficiënter!

voorbeeld:
public void liftSpeed (speed) {
       liftMotor.setPower(speed);
}

2024-10-24 14:56 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Lift.java
> +}
Zelfde voor de servo als de motor. 1 functie voor de snelheid en dan de snelheid zetten in TeleOp

2024-10-24 14:56 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Lift.java
> +}
Stopt de servo automatisch als je de knop loslaat? Zo ja, moet dat? Zo nee, moet dat?

2024-10-24 14:56 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
Dit subsystem mag weg, de werkende drivetrain zit al in Master.

2024-10-24 14:56 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
Probeer even wat knoppen combinaties, je hebt nu alleen de Dpad gebruikt. Als dat handig is, prima, maar misschien zijn andere knoppen handiger?

2024-10-24 15:14 UTC, MarkKonijnenburg requested changes
Nog ff wat aangepast
Let op! bij de 1ste x zei ik verwijder maar de drivetrain, DOE DIT NIET!
Is foutje van mijj

2024-10-24 15:14 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
> +//        rightBack.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
Is dit nog nuttig? of kan het weg?

2024-10-24 15:14 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
> +        rightBack.setPower((y + x + rx));
Je formules voor het omrekenen van de individuele snelheden komen niet overeen. Heb je jou code getest? Werkt het?
Want bij mijn weten werkte de master code volledig. Wat is je reden van aanpassing?

2024-10-24 15:46 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
> +import org.firstinspires.ftc.teamcode.robot.subsystem.Lift;
ik zie die maar 1x staan?

2024-10-24 15:52 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/Lift.java
> +}
ja hij doet dit automatisch en dit is de bedoeling.

2024-10-24 15:53 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
nu heten ze beide TeleOP

2024-10-24 16:00 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
> +        rightFront.setDirection(DcMotor.Direction.REVERSE);
bij mij is alleen links omgewisseld

2024-10-24 16:00 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
> +//        rightBack.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
dit is gedaan omdat we dit wel willen gaan gebruiken, maar omdat er een encoder kabel het niet doet hij anders heel raar doet.

2024-10-24 16:02 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
> +        rightBack.setPower((y + x + rx));
ik had dit aangepast omdat hij de verkeerde kanten op reed en draaiden. dus als ik naar links wilden draaien of rijden reed of draaide hij naar rechts

2024-10-24 16:26 UTC, MarkKonijnenburg requested changes
BIJNAAAA:)

2024-10-24 16:26 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
> +        }
Kan je niet een y-as van een joystick gebruiken? Dan kan je meteen als gebruiker de snelheid aanpassen. Of is dit een slecht idee? Wat is jou mening?

2024-10-24 16:26 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
Ehm, nu MecanumDrivetrain weg is, en je dit in de master gaat zetten. Gaat heel de drivetrain uit master. Dit is natuurlijk niet de bedoeling. Hoe je dit handig kan fixen is een pull request te doen om de Master in de Lift te gooien. Ik kijk ff of ik dit kan fixennn

2024-10-24 16:29 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
> +        }
je hoeft dan geen if statement meer te maken

voorbeeld (kan je niet 100% copy pasten):
subsystem.set(joystick.y)

2024-10-24 16:31 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
Ik zie nu dat wat ik zei niet kan, ik ga ff verder koekeloeren. Tenzij je zelf de drivetrain er terug in kan zetten

2024-10-24 17:45 UTC, Sebastiaap commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
er is toch ook een Drivetreain branch? kan deze niet gewoon in master gezet worden?

2024-10-25 10:14 UTC, MarkKonijnenburg approved these changes
Ik vind het helemaal mooi
miss nog 1 dingetje aanpassen maar is niet noodzakelijk, alleen misschien handiger voor de bestuurder van de robot

2024-10-25 10:14 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/opmode/teleop/TeleOP.java
> +        }
Is het miss een idee om de servo automatisch terug naar zijn positie te zetten? Dus als je de bumper indrukt dat hij dan beweegt naar de goede positie, en als je de bumper weer los laat hij automatisch terug naar zijn horizontale positie gaat?

Voorbeeld:
if (....) {
doe dit
} else {
doe ff naar horizontale positie gaan}


Als je anders van mening bent of het zo beter vindt, ook goed he! Maar miss een idee...

2024-10-25 10:14 UTC, MarkKonijnenburg commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/robot/subsystem/MecanumDrivetrain.java
Kunnen we voor nu doen, maar is in principe dubbel werk. Voortaan mag je heb er dus gewoon inlaten.

2024-10-27 16:16 UTC, merged